### ISSUE TITLE
Stuff

### ISSUE THREAD

**Issue by tannerghosen** [tannerghosen/Stuff#3]
Stuff!

**Comment by tanner-ghosen** [comment]
#3

**Comment by tanner-ghosen** [comment]
Note to self: Resize TRASHMAN.gif to an appropriate size. No rush, however.

**Comment by tannerghosen** [comment]
01101100 01101111 01101100

**Comment by tannerghosen** [comment]
Upload the Senior Project once it's submitted on 6/4/17
